import Footer from "../components/footer"
import DAppNavbar from "../dapp/components/navbar";
import { Providers } from "../dapp/providers";
import "../globals.css";
import '@rainbow-me/rainbowkit/styles.css'; // rainbowkit styles

export const metadata = {
  title: 'Stratergy',
  description: 'Generated by Next.js',
}

export default function StratergyLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
            <DAppNavbar/>
              {children}
            <Footer/>
        </Providers>
      </body>
    </html>
  )
}
