import Footer from "../components/footer"
import Navbar from "../components/navbar";
import "../globals.css";
import '@rainbow-me/rainbowkit/styles.css'; // rainbowkit styles

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Navbar/>
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
